import { z } from 'zod';

export const loginSchema = z.object({
  email: z.string().email('Insira um e-mail válido'),
  password: z.string().min(6, 'A senha deve ter no mínimo 6 caracteres'),
});

export const recipeSchema = z.object({
  name: z.string().min(3, 'Nome deve ter no mínimo 3 caracteres'),
  slug: z.string().min(3, 'Slug é obrigatório'),
  shortDescription: z.string().min(10, 'Descrição curta deve ter no mínimo 10 caracteres'),
  fullDescription: z.string().min(20, 'Descrição completa deve ter no mínimo 20 caracteres'),
  difficulty: z.enum(['Fácil', 'Médio', 'Difícil', 'Chef']),
  cost: z.enum(['Baixo', 'Médio', 'Alto']),
  prepTimeMinutes: z.number().min(0, 'Valor inválido'),
  cookTimeMinutes: z.number().min(0, 'Valor inválido'),
  totalTimeMinutes: z.number().min(1, 'Tempo total deve ser maior que 0'),
  servings: z.number().min(1, 'Deve render ao menos 1 porção'),
  categories: z.array(z.string()).min(1, 'Selecione ao menos uma categoria'),
  goals: z.array(z.string()),
  diets: z.array(z.string()),
  mealTypes: z.array(z.string()),
  tags: z.array(z.string()),
  calories: z.number().min(0),
  proteins: z.number().min(0),
  carbs: z.number().min(0),
  fats: z.number().min(0),
  fiber: z.number().optional(),
  sodium: z.number().optional(),
  saturatedFats: z.number().optional(),
  imageUrl: z.string().optional(),
  imageAssetKey: z.string().optional(),
  videoUrl: z.string().optional(),
  videoAssetKey: z.string().optional(),
  altText: z.string().optional(),
});

export const ingredientSchema = z.object({
  name: z.string().min(2, 'Nome é obrigatório'),
  category: z.string().min(2, 'Categoria é obrigatória'),
  defaultUnit: z.string().min(1, 'Unidade é obrigatória'),
  calories: z.number().min(0),
  proteins: z.number().min(0),
  carbs: z.number().min(0),
  fats: z.number().min(0),
  fiber: z.number().optional(),
  sodium: z.number().optional(),
  source: z.string().optional(),
});

export const exerciseSchema = z.object({
  name: z.string().min(3, 'Nome deve ter no mínimo 3 caracteres'),
  slug: z.string().min(3, 'Slug é obrigatório'),
  shortDescription: z.string().min(10, 'Descrição curta é obrigatória'),
  fullDescription: z.string().min(20, 'Descrição completa é obrigatória'),
  category: z.string().min(1, 'Selecione a categoria'),
  movementPattern: z.string().min(1, 'Selecione o padrão de movimento'),
  primaryMuscleGroup: z.string().min(1, 'Selecione o grupo muscular principal'),
  level: z.enum(['Iniciante', 'Intermediário', 'Avançado']),
  impact: z.enum(['Baixo', 'Médio', 'Alto']),
  complexity: z.enum(['Simples', 'Moderada', 'Técnica']),
  startingPosition: z.string().min(5, 'Posição inicial é obrigatória'),
  executionStepsText: z.string().min(10, 'Insira os passos de execução (um por linha)'),
  breathingGuide: z.string().min(5, 'Guia de respiração é obrigatório'),
  commonMistakesText: z.string().optional(),
  precautionsText: z.string().optional(),
  stopConditionsText: z.string().optional(),
  suggestedSets: z.number().min(1),
  minReps: z.number().optional(),
  maxReps: z.number().optional(),
  durationSeconds: z.number().optional(),
  restSeconds: z.number().min(0),
  imageUrl: z.string().optional(),
  imageAssetKey: z.string().optional(),
  videoUrl: z.string().optional(),
  videoAssetKey: z.string().optional(),
});

export const announcementSchema = z.object({
  title: z.string().min(3, 'Título é obrigatório'),
  message: z.string().min(10, 'Mensagem deve ter no mínimo 10 caracteres'),
  type: z.enum(['information', 'warning', 'maintenance', 'update', 'content']),
  audience: z.enum(['all', 'new_users', 'active_subscribers']),
  startAt: z.string().min(1, 'Data de início é obrigatória'),
  endAt: z.string().optional(),
  priority: z.number().min(1).max(10),
  actionLabel: z.string().optional(),
  actionRoute: z.string().optional(),
  active: z.boolean(),
});
